language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  # For Pandas version 0.14.
  - sudo cat /etc/apt/sources.list /etc/apt/sources.list.d/*
  - sudo add-apt-repository "deb http://ppa.launchpad.net/pythonxy/pythonxy-devel/ubuntu raring main" -y
  # - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ utopic main restricted universe" -y
  - sudo apt-get update -qq
  - sudo apt-cache policy python-pandas python-pandas-lib python-numpy
  - sudo apt-cache show python-pandas python-pandas-lib python-numpy
  - sudo apt-get install python-numpy python-pandas python-pandas-lib python-tables python-yaml
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install sas7bdat
  - pip install click
  - pip install -r requirements.txt
script: make test-ci
